classyllama/ClassyLlama_AvaTax

etc/di.xml

Fixes setup:di:compile issues

---

etc/di.xml

Reverts classyllama/ClassyLlama_AvaTax#12
See comment here for explanation: https://github.com/classyllama/ClassyLlama_AvaTax/pull/12#issuecomment-219154868

Revert "Fixes setup:di:compile issues"

---

Framework/Interaction/Line.php
Framework/Interaction/Tax.php

This addresses issue #39
Technical Details:
\Magento\Tax\Model\Calculation\AbstractAggregateCalculator::calculateWithTaxNotInPrice
makes a call to get the discount amount $item->getDiscountAmount()
but the shipping item returns a null value for the discount amount causing it to calculate tax on the shipping item regardless.
The items that are passed into the calculation routines come from
\Magento\Tax\Model\Sales\Total\Quote\Tax::collect
\Magento\Tax\Model\Sales\Total\Quote\Tax::getQuoteTaxDetails
Starts building $itemDataObjects for normal quote items via $this->mapItems()
\Magento\Tax\Model\Sales\Total\Quote\CommonTaxCollector::mapItems
which is builds from getting the details out of the ShippingAssignmentInterface item data.
It then gets the shipping item via …

#421_41 - Accommodate shipping discount in tax calculation

---

CHANGELOG.md
Observer/ConfigSaveObserver.php

- Update change log
- Revise code to present verbose warning instead of error when
credentials are incomplete

#421_51 - Revise empty credential error

---

CHANGELOG.md
Framework/AppInterface.php
Framework/Interaction/Tax.php
composer.json

- Add code to send Magento order number to Avatax as “Reference Code”

#421_55 - Send Magento Order Id to Avatax

---

Helper/Config.php

- Refactor code to correctly use origin address line 2

#421_61 - Fix Origin Address In Request

---

view/frontend/templates/init_validation_modal.phtml

- Add JS to define baseUrl with correct value

#AVS-421_63 - jQuery error during address validation

---

Api/Data/GrandTotalDetailsInterface.php
Api/Data/GrandTotalRatesInterface.php
Framework/Interaction/TaxCalculation.php
Model/Quote/GrandTotalDetailsPlugin.php
Model/Tax/Calculation/GrandTotalRates.php
Plugin/Sales/Total/Quote/CommonTaxCollector.php
etc/adminhtml/system.xml
etc/di.xml
etc/extension_attributes.xml
view/frontend/requirejs-config.js
view/frontend/web/template/checkout/cart/totals/tax.html
view/frontend/web/template/checkout/summary/tax.html

- Add extension attribute to rates to hold tax value
- Add new interface to add extension attribute methods
- Add template overrides to display tax summary details on frontend in
cart and checkout
- Addresses GitHub Issue #70

#AVS-421_64 - Add Tax Summary

---

Api/Data/GrandTotalDetailsInterface.php
Api/Data/GrandTotalRatesInterface.php
Framework/Interaction/TaxCalculation.php
Model/Quote/GrandTotalDetailsPlugin.php
Model/Tax/Calculation/GrandTotalRates.php
Plugin/Sales/Total/Quote/CommonTaxCollector.php
etc/adminhtml/system.xml
etc/di.xml
etc/extension_attributes.xml
view/frontend/requirejs-config.js
view/frontend/web/js/addressValidation.js
view/frontend/web/template/checkout/cart/totals/tax.html
view/frontend/web/template/checkout/summary/tax.html

AVS-421_67 - Revise for Magento 2.2 compatibility
- Refactor code to be fully compatible with Magento 2.2 while retaining
backwards compatibility with 2.1
- Includes changes in https://github.com/classyllama/ClassyLlama_AvaTax/pull/90
- Addresses Issue #85

Feature/avs 421 67 revise for magento 2.2 compatibility

---

Model/Quote/GrandTotalDetailsPluginAbstract.php

- Remove unused code from constructor

AVS-421_67 - Revise for Magento 2.2 compatibility

---

Helper/TaxClass.php

- Refactor code to retrieve product ID in a different manner
- Fixes issue #94

AVS-421_72 - Fix getId exception

---

view/frontend/web/js/addressValidation.js
view/frontend/web/js/view/address-validation-modal.js

- Add code to conditionally submit form natively based on AvaTax address
validation config setting
- Addresses issue #108

AVS-421_76 - Fix address validation bug

---

view/frontend/web/js/view/address-validation-modal.js

- Add function to enable submit button on address edit
- Fixes issue #110

AVS-421_77 - Fix Address Validation Bug

---

Model/Config/Source/CustomerCode.php
etc/adminhtml/system.xml

- Refactor code to include all customer attributes as customer code
options in backend
- Update config setting note to reflect new behavior

AVS-421_74 - Expand Customer Code Options

---

Plugin/Checkout/Model/ShippingInformationManagement.php

- Add try/catch and replace customer-facing error message with one that
is more verbose and informational
- Addresses issue #132

AVS-421_95 - Checkout error with updated address

---

view/frontend/web/js/view/address-validation-modal.js

- Add JS to enable save button when address validation modal is closed
- Addresses issue #139

AVS-421_92 - Save button remains disabled

---

view/frontend/layout/checkout_index_index.xml
view/frontend/requirejs-config.js
view/frontend/web/css/source/_module.less
view/frontend/web/js/view/estimation/mixin.js
view/frontend/web/template/estimation.html

Enhance mobile display of checkout summary

---

Framework/Interaction/Tax.php
Framework/Interaction/Tax/Get.php
Helper/CustomsConfig.php
Model/Plugin/CartTotalRepository.php
Model/Tax/Sales/Total/Quote/Tax.php
Setup/UpgradeData.php
Setup/UpgradeSchema.php
Ui/Component/Listing/Columns/CrossBorderClassActions.php
etc/di.xml
etc/extension_attributes.xml
etc/module.xml
view/frontend/layout/checkout_cart_index.xml
view/frontend/layout/checkout_index_index.xml
view/frontend/web/template/checkout/cart/totals/grand-total.html
view/frontend/web/template/checkout/cart/totals/tax.html
view/frontend/web/template/checkout/summary/grand-total.html

Add display for non-passthrough customs tax

---

view/frontend/web/js/view/estimation/mixin.js
view/frontend/web/template/estimation.html

Enhance mobile display of non-passthough customs tax

---

Plugin/Tax/Model/Sales/Total/Quote/Shipping.php

- Add code to set shipping amounts on total object
- Addresses issue #184

AVS-421_104 - Shipping is zeroed at checkout

---

view/adminhtml/layout/customer_index_edit.xml

- Remove errant line in XML file
- Addresses issue #151.

AVS-421_107 - Fix no orders tab on customer edit form

---

Framework/Interaction/TaxCalculation.php

Previously we didn't have data in the SOAP request for line item details breakdown of different taxes per item. With the REST api, now we do, and no longer have to inaccurately determine the individual taxes at an item level.

AVA-555_85 - Refactor item tax to be pulled from AvaTax details instead of summary

---

Framework/Interaction/Tax.php

- Refactor VAT ID code to match the behavior described in the config
comment

AVS-421_88 - Fix Submit VAT Number

---

Framework/Interaction/TaxCalculation.php

- Remove rounding from displayed tax rate
- Addresses issue #179

AVS-421_110 - Increase tax rate display precision

---

Model/Config/Source/RegionFilterList.php
Model/Config/Source/TaxCalculationCountries.php
composer.json

@rsisco I've tested invoicing, credit memo-ing, and tax calculation/estimation on this branch for 2.1, 2.2, and 2.3 and have not had any issues. I believe we can merge this branch to add support for Magento 2.3
Addresses issue #137

Feature/avs 421 108 magento 2.3 support

---

Model/Config/Source/RegionFilterList.php
Model/Config/Source/TaxCalculationCountries.php
composer.json

Adds Magento 2.3 support (see #216)

AVS-421_109 - Magento 2.3 compatibility changes
